# Generated by Django 3.2.9 on 2021-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='upload',
        ),
    ]
